# Generated by Django 5.2.6 on 2026-07-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_is_finished"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="dealer",
            new_name="creator",
        ),
    ]
