# Generated by Django 5.2.6 on 2026-07-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_dealer_order_creator"),
        ("users", "0006_alter_profile_options_alter_profile_percentage_sale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.buyer",
                verbose_name="Покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="order",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery",
            field=models.PositiveIntegerField(verbose_name="Доставка"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="Завершен"),
        ),
    ]
