# Generated by Django 5.2.6 on 2026-07-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_buyer_alter_order_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="percentage_worker",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="процент работника",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_sum",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=11,
                verbose_name="стоимость всего заказа",
            ),
        ),
    ]
