# Generated by Django 5.2.6 on 2026-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_percentage_worker_order_total_sum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_finished",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Заказано"),
                    ("in_work", "В работе"),
                    ("done", "Выполнено"),
                    ("cancelled", "Отменено"),
                ],
                default="ordered",
                max_length=100,
                verbose_name="Цвет фурнитуры",
            ),
        ),
    ]
