# Generated by Django 5.2.6 on 2026-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_is_finished_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="installation_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=11,
                verbose_name="Стоимость монтажа",
            ),
        ),
    ]
