# Generated by Django 5.2.6 on 2026-08-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_installation_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="profit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=11, verbose_name="Прибыль"
            ),
        ),
    ]
