# Generated by Django 5.2.6 on 2026-06-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField()),
                ("identity", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                (
                    "coverage_rate_doors",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "coverage_rate_sash",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Glass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlukharGlass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("min_area", models.PositiveIntegerField()),
                ("max_area", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "calculate_glukhar_glass",
            },
        ),
        migrations.CreateModel(
            name="GlukharWood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "calculate_glukhar_wood",
            },
        ),
        migrations.CreateModel(
            name="Hardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortalWood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ratio", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "calculate_portal_wood",
            },
        ),
        migrations.CreateModel(
            name="ProfitRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ratio", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "calculate_profit_ratio",
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название схемы")),
                (
                    "min_size",
                    models.PositiveIntegerField(verbose_name="Мин. размер (мм)"),
                ),
                (
                    "max_size",
                    models.PositiveIntegerField(verbose_name="Макс. размер (мм)"),
                ),
                ("door", models.PositiveIntegerField()),
                ("fixed_sash", models.PositiveIntegerField()),
                ("rail_amour", models.PositiveIntegerField()),
                ("door_sub", models.PositiveIntegerField()),
                ("sash_sub", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beam", models.CharField(max_length=50)),
                ("carpenter", models.DecimalField(decimal_places=2, max_digits=10)),
                ("painter", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Glukhar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="Ширина")),
                ("height", models.PositiveIntegerField(verbose_name="Высота")),
                ("is_finished", models.BooleanField(default=False)),
                ("amount", models.PositiveIntegerField(verbose_name="Количество")),
                ("calculation_details", models.JSONField(blank=True)),
                (
                    "is_non_rectangular",
                    models.BooleanField(default=False, verbose_name="Не_прямоугольник"),
                ),
                (
                    "color_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.color"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.order"
                    ),
                ),
                (
                    "wood_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calculate.glukharwood",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Portal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="Ширина")),
                ("height", models.PositiveIntegerField(verbose_name="Высота")),
                ("is_finished", models.BooleanField(default=False)),
                ("amount", models.PositiveIntegerField(verbose_name="Количество")),
                ("calculation_details", models.JSONField(blank=True)),
                (
                    "hardware_color",
                    models.CharField(
                        choices=[
                            ("silver", "Серебро"),
                            ("bronze", "Бронза"),
                            ("white", "Белый"),
                            ("brown", "Коричневый"),
                        ],
                        default="white",
                        max_length=100,
                    ),
                ),
                (
                    "has_rain_protection",
                    models.BooleanField(default=False, verbose_name="Есть_ли_дождь"),
                ),
                (
                    "color_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.color"
                    ),
                ),
                (
                    "glass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.glass"
                    ),
                ),
                (
                    "hardware_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calculate.hardware",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.order"
                    ),
                ),
                (
                    "wood_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calculate.portalwood",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.scheme"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
