# Generated by Django 5.2.6 on 2026-06-09 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                (
                    "coverage_rate_doors",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "coverage_rate_sash",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Glass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlukharGlass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("min_area", models.PositiveIntegerField()),
                ("max_area", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название_схемы")),
                (
                    "min_width",
                    models.PositiveIntegerField(verbose_name="Мин._ширина_(мм)"),
                ),
                (
                    "max_width",
                    models.PositiveIntegerField(verbose_name="Макс._ширина_(мм)"),
                ),
                (
                    "min_height",
                    models.PositiveIntegerField(verbose_name="Мин._высота_(мм)"),
                ),
                (
                    "max_height",
                    models.PositiveIntegerField(verbose_name="Макс._высота_(мм)"),
                ),
                ("door", models.PositiveIntegerField()),
                ("fixed_sash", models.PositiveIntegerField()),
                ("rail_amour", models.PositiveIntegerField()),
                ("door_sub", models.PositiveIntegerField()),
                ("sash_sub", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Wood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beam", models.CharField(max_length=50)),
                ("carpenter", models.DecimalField(decimal_places=2, max_digits=10)),
                ("painter", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="HsPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="Ширина")),
                ("height", models.PositiveIntegerField(verbose_name="Высота")),
                (
                    "has_delivery",
                    models.BooleanField(default=False, verbose_name="Доставка"),
                ),
                (
                    "has_installation",
                    models.BooleanField(default=False, verbose_name="Монтаж"),
                ),
                (
                    "has_unloading",
                    models.BooleanField(default=False, verbose_name="Разгрузка"),
                ),
                (
                    "has_discount",
                    models.BooleanField(default=False, verbose_name="Скидка"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "has_rain_protection",
                    models.BooleanField(default=False, verbose_name="Есть_ли_дождь"),
                ),
                (
                    "color_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.color"
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "glass_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calculate.glukharglass",
                    ),
                ),
                (
                    "hardware_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calculate.hardware",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.scheme"
                    ),
                ),
                (
                    "wood_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.wood"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixedWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="Ширина")),
                ("height", models.PositiveIntegerField(verbose_name="Высота")),
                (
                    "has_delivery",
                    models.BooleanField(default=False, verbose_name="Доставка"),
                ),
                (
                    "has_installation",
                    models.BooleanField(default=False, verbose_name="Монтаж"),
                ),
                (
                    "has_unloading",
                    models.BooleanField(default=False, verbose_name="Разгрузка"),
                ),
                (
                    "has_discount",
                    models.BooleanField(default=False, verbose_name="Скидка"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_non_rectangular",
                    models.BooleanField(default=False, verbose_name="Не_прямоугольник"),
                ),
                (
                    "color_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.color"
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "glass_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calculate.glukharglass",
                    ),
                ),
                (
                    "wood_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="calculate.wood"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
