# Generated by Django 5.2.6 on 2026-06-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheme",
            name="max_height",
        ),
        migrations.RemoveField(
            model_name="scheme",
            name="max_width",
        ),
        migrations.RemoveField(
            model_name="scheme",
            name="min_height",
        ),
        migrations.RemoveField(
            model_name="scheme",
            name="min_width",
        ),
        migrations.AddField(
            model_name="scheme",
            name="max_size",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Макс._размер_(мм)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="min_size",
            field=models.PositiveIntegerField(
                default="1", verbose_name="Мин._размер_(мм)"
            ),
            preserve_default=False,
        ),
    ]
