# Generated by Django 5.2.6 on 2026-07-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0001_initial"),
        ("orders", "0003_rename_dealer_order_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Коэффициент прибыли",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="beams",
            name="identity",
            field=models.CharField(max_length=50, verbose_name="Идентификатор"),
        ),
        migrations.AlterField(
            model_name="beams",
            name="length",
            field=models.PositiveIntegerField(verbose_name="Длина"),
        ),
        migrations.AlterField(
            model_name="beams",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="beams",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="color",
            name="coverage_rate_doors",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Норма расхода на двери"
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="coverage_rate_sash",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Норма расхода на створки"
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="color",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="glass",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="glass",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="glukhar",
            name="calculation_details",
            field=models.JSONField(blank=True, verbose_name="Детали расчета"),
        ),
        migrations.AlterField(
            model_name="glukhar",
            name="color_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="calculate.color",
                verbose_name="Тип цвета",
            ),
        ),
        migrations.AlterField(
            model_name="glukhar",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="Готово"),
        ),
        migrations.AlterField(
            model_name="glukhar",
            name="is_non_rectangular",
            field=models.BooleanField(default=False, verbose_name="Не прямоугольник"),
        ),
        migrations.AlterField(
            model_name="glukhar",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="glukhar",
            name="wood_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="calculate.glukharwood",
                verbose_name="Тип дерева",
            ),
        ),
        migrations.AlterField(
            model_name="glukharglass",
            name="max_area",
            field=models.PositiveIntegerField(verbose_name="Макс. площадь"),
        ),
        migrations.AlterField(
            model_name="glukharglass",
            name="min_area",
            field=models.PositiveIntegerField(verbose_name="Мин. площадь"),
        ),
        migrations.AlterField(
            model_name="glukharglass",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="glukharglass",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="glukharwood",
            name="length",
            field=models.PositiveIntegerField(verbose_name="Длина"),
        ),
        migrations.AlterField(
            model_name="glukharwood",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="glukharwood",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="length",
            field=models.PositiveIntegerField(verbose_name="Длина"),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="portal",
            name="calculation_details",
            field=models.JSONField(blank=True, verbose_name="Детали расчета"),
        ),
        migrations.AlterField(
            model_name="portal",
            name="color_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="calculate.color",
                verbose_name="Тип цвета",
            ),
        ),
        migrations.AlterField(
            model_name="portal",
            name="glass",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="calculate.glass",
                verbose_name="Стекло",
            ),
        ),
        migrations.AlterField(
            model_name="portal",
            name="hardware_color",
            field=models.CharField(
                choices=[
                    ("silver ", "Серебро "),
                    ("bronze ", "Бронза "),
                    ("white ", "Белый "),
                    ("brown ", "Коричневый "),
                ],
                default="white ",
                max_length=100,
                verbose_name="Цвет фурнитуры",
            ),
        ),
        migrations.AlterField(
            model_name="portal",
            name="hardware_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="calculate.hardware",
                verbose_name="Тип фурнитуры",
            ),
        ),
        migrations.AlterField(
            model_name="portal",
            name="has_rain_protection",
            field=models.BooleanField(
                default=False, verbose_name="Есть ли защита от дождя"
            ),
        ),
        migrations.AlterField(
            model_name="portal",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="Готово"),
        ),
        migrations.AlterField(
            model_name="portal",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="portal",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="calculate.scheme",
                verbose_name="Схема",
            ),
        ),
        migrations.AlterField(
            model_name="portal",
            name="wood_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="calculate.portalwood",
                verbose_name="Тип дерева",
            ),
        ),
        migrations.AlterField(
            model_name="portalwood",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="portalwood",
            name="ratio",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Коэффициент"
            ),
        ),
        migrations.AlterField(
            model_name="profitratio",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="profitratio",
            name="ratio",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Коэффициент прибыли"
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="door",
            field=models.PositiveIntegerField(verbose_name="Дверь"),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="door_sub",
            field=models.PositiveIntegerField(verbose_name="Дверной подстав"),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="fixed_sash",
            field=models.PositiveIntegerField(verbose_name="Фиксированная створка"),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="rail_amour",
            field=models.PositiveIntegerField(verbose_name="Рейка арматура"),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="sash_sub",
            field=models.PositiveIntegerField(verbose_name="Створочный подстав"),
        ),
        migrations.AlterField(
            model_name="work",
            name="beam",
            field=models.CharField(max_length=50, verbose_name="Брус"),
        ),
        migrations.AlterField(
            model_name="work",
            name="carpenter",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Столяр"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="painter",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Маляр"
            ),
        ),
    ]
