# Generated by Django 5.2.6 on 2026-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0002_remove_scheme_max_height_remove_scheme_max_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beams",
            name="identity",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
