# Generated by Django 5.2.6 on 2026-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculate",
            "0002_scheme_ratio_alter_beams_identity_alter_beams_length_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="portal",
            name="hardware_color",
            field=models.CharField(
                choices=[
                    ("silver ", "Серебро"),
                    ("bronze ", "Бронза"),
                    ("white ", "Белый"),
                    ("brown ", "Коричневый"),
                ],
                default="white ",
                max_length=100,
                verbose_name="Цвет фурнитуры",
            ),
        ),
    ]
