# Generated by Django 5.2.6 on 2026-06-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0003_beams_identity"),
        ("users", "0004_buyer_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedwindow",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.buyer",
            ),
        ),
        migrations.AddField(
            model_name="hsportal",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.buyer",
            ),
        ),
    ]
