# Generated by Django 5.2.6 on 2026-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0003_alter_portal_hardware_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedExpenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="profitratio",
            name="ratio",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Коэффициент"
            ),
        ),
    ]
