# Generated by Django 5.2.6 on 2026-08-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0004_fixedexpenses_alter_profitratio_ratio"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="fixedexpenses",
            table="calculate_fixed_expenses",
        ),
    ]
