# Generated by Django 5.2.6 on 2026-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0004_fixedwindow_buyer_hsportal_buyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixedwindow",
            name="has_delivery",
        ),
        migrations.RemoveField(
            model_name="fixedwindow",
            name="has_discount",
        ),
        migrations.RemoveField(
            model_name="fixedwindow",
            name="has_installation",
        ),
        migrations.RemoveField(
            model_name="fixedwindow",
            name="has_unloading",
        ),
        migrations.RemoveField(
            model_name="hsportal",
            name="has_delivery",
        ),
        migrations.RemoveField(
            model_name="hsportal",
            name="has_discount",
        ),
        migrations.RemoveField(
            model_name="hsportal",
            name="has_installation",
        ),
        migrations.RemoveField(
            model_name="hsportal",
            name="has_unloading",
        ),
        migrations.AddField(
            model_name="fixedwindow",
            name="delivery",
            field=models.PositiveIntegerField(default=False, verbose_name="Доставка"),
        ),
        migrations.AddField(
            model_name="fixedwindow",
            name="discount",
            field=models.PositiveIntegerField(default=False, verbose_name="Скидка"),
        ),
        migrations.AddField(
            model_name="fixedwindow",
            name="installation",
            field=models.PositiveIntegerField(default=False, verbose_name="Монтаж"),
        ),
        migrations.AddField(
            model_name="fixedwindow",
            name="unloading",
            field=models.PositiveIntegerField(default=False, verbose_name="Разгрузка"),
        ),
        migrations.AddField(
            model_name="hsportal",
            name="delivery",
            field=models.PositiveIntegerField(default=False, verbose_name="Доставка"),
        ),
        migrations.AddField(
            model_name="hsportal",
            name="discount",
            field=models.PositiveIntegerField(default=False, verbose_name="Скидка"),
        ),
        migrations.AddField(
            model_name="hsportal",
            name="installation",
            field=models.PositiveIntegerField(default=False, verbose_name="Монтаж"),
        ),
        migrations.AddField(
            model_name="hsportal",
            name="unloading",
            field=models.PositiveIntegerField(default=False, verbose_name="Разгрузка"),
        ),
    ]
