# Generated by Django 5.2.6 on 2026-06-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0005_remove_fixedwindow_has_delivery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Коэффициент прибыли"
                    ),
                ),
            ],
        ),
    ]
