# Generated by Django 5.2.6 on 2026-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0006_profitratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profitratio",
            name="ratio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profitratio",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
