# Generated by Django 5.2.6 on 2026-06-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0007_profitratio_ratio_alter_profitratio_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hsportal",
            name="hardware_color",
            field=models.CharField(
                choices=[
                    ("silver", "Серебро"),
                    ("bronze", "Бронза"),
                    ("white", "Белый"),
                    ("brown", "Коричневый"),
                ],
                default="white",
                max_length=100,
            ),
        ),
    ]
