# Generated by Django 5.2.6 on 2026-06-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0008_hsportal_hardware_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedwindow",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hsportal",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
