# Generated by Django 5.2.6 on 2026-06-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0009_fixedwindow_is_finished_hsportal_is_finished"),
    ]

    operations = [
        migrations.CreateModel(
            name="WoodPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ratio", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameModel(
            old_name="Wood",
            new_name="WoodGlukhar",
        ),
        migrations.AlterField(
            model_name="hsportal",
            name="wood_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="calculate.woodportal"
            ),
        ),
    ]
