# Generated by Django 5.2.6 on 2026-06-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0010_woodportal_rename_wood_woodglukhar_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="woodglukhar",
            table="wood_glukhar",
        ),
    ]
