# Generated by Django 5.2.6 on 2026-06-12 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0011_alter_woodglukhar_table"),
        ("users", "0004_buyer_alter_profile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FixedWindow",
            new_name="Glukhar",
        ),
        migrations.RenameModel(
            old_name="WoodGlukhar",
            new_name="GlukharWood",
        ),
        migrations.RenameModel(
            old_name="HsPortal",
            new_name="Portal",
        ),
        migrations.RenameModel(
            old_name="WoodPortal",
            new_name="PortalWood",
        ),
        migrations.AlterModelTable(
            name="glukharglass",
            table="calculate_glukhar_glass",
        ),
        migrations.AlterModelTable(
            name="glukharwood",
            table="calculate_glukhar_wood",
        ),
        migrations.AlterModelTable(
            name="portalwood",
            table="calculate_portal_wood",
        ),
        migrations.AlterModelTable(
            name="profitratio",
            table="calculate_profit_ratio",
        ),
    ]
