# Generated by Django 5.2.6 on 2026-06-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0012_rename_fixedwindow_glukhar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glukhar",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Скидка"
            ),
        ),
        migrations.AlterField(
            model_name="portal",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Скидка"
            ),
        ),
    ]
