# Generated by Django 5.2.6 on 2026-06-13 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0013_alter_glukhar_discount_alter_portal_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portal",
            name="glass_type",
        ),
        migrations.AddField(
            model_name="portal",
            name="glass",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="calculate.glass",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scheme",
            name="max_size",
            field=models.PositiveIntegerField(verbose_name="Макс. размер (мм)"),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="min_size",
            field=models.PositiveIntegerField(verbose_name="Мин. размер (мм)"),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название схемы"),
        ),
    ]
