# Generated by Django 5.2.6 on 2026-06-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0014_remove_portal_glass_type_portal_glass_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glukhar",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="glukhar",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="glukhar",
            name="dealer",
        ),
        migrations.RemoveField(
            model_name="glukhar",
            name="delivery",
        ),
        migrations.RemoveField(
            model_name="glukhar",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="glukhar",
            name="glass_type",
        ),
        migrations.RemoveField(
            model_name="glukhar",
            name="installation",
        ),
        migrations.RemoveField(
            model_name="glukhar",
            name="unloading",
        ),
        migrations.RemoveField(
            model_name="portal",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="portal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="portal",
            name="dealer",
        ),
        migrations.RemoveField(
            model_name="portal",
            name="delivery",
        ),
        migrations.RemoveField(
            model_name="portal",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="portal",
            name="installation",
        ),
        migrations.RemoveField(
            model_name="portal",
            name="unloading",
        ),
    ]
