# Generated by Django 5.2.6 on 2026-06-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0015_remove_glukhar_buyer_remove_glukhar_created_at_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glukhar",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.order",
                null=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portal",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.order",
                null=True
            ),
            preserve_default=False,
        ),
    ]
