# Generated by Django 5.2.6 on 2026-06-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0016_glukhar_order_portal_order"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glukhar",
            name="amount",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portal",
            name="amount",
            field=models.PositiveIntegerField(default="1", verbose_name="Количество"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="glukhar",
            name="order",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="orders.order"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portal",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.order",
            ),
            preserve_default=False,
        ),
    ]
