# Generated by Django 5.2.6 on 2026-06-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("dealer", "Дилер"),
                    ("carpenter", "Столяр"),
                    ("buyer", "покупатель"),
                ],
                default="dealer",
                max_length=100,
                verbose_name="роль",
            ),
        ),
    ]
