# Generated by Django 5.2.6 on 2026-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_squashed_0005_alter_profile_percentage_sale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "данные пользователя",
                "verbose_name_plural": "данные пользователей",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="percentage_sale",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="процент с продажи"
            ),
        ),
    ]
